name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      - name: semantic release
        uses: cycjimmy/semantic-release-action@v4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: main