name: Renovate

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: log level override
        required: false
        default: info
        type: string
      overrideSchedule:
        description: schedule override
        required: false
        default: 'false'
        type: string
  schedule:
    - cron: '0 16 * * *'

jobs:
  call-workflow:
    uses: justsomescripts/renovate-config/.github/workflows/renovate.yml@main
    with:
      logLevel: ${{ inputs.logLevel || 'info' }}
      overrideSchedule: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
    secrets: inherit
